django/conference/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views


urlpatterns = [
    # path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("secondary", views.register_secondary, name="secondary"),
    path("third", views.register_third, name="third"),
    path("staff", views.register_staff, name="staff"),

    path("profile", views.profile, name="profile"),
    path("article/<int:article_id>", views.article, name="article"),
    path("article/<int:article_id>/<str:need_check>", views.article, name="article"),
    path("library", views.library, name="library"),
    path("join", views.join_view, name="join"),
    path("comment/<int:article_id>", views.comment, name="comment"),

    path("download_text/<int:article_id>", views.download_article_text, name="download_text"),
    path("download_thesis/<int:article_id>", views.download_article_thesis, name="download_thesis"),
    path("download_consent/<int:user_id>", views.download_consent, name="download_consent"),
    path("download_attachment/<int:attachment_id>", views.download_attachment, name="download_attachment"),
    path("delete_text/<int:article_id>", views.delete_article_text, name="delete_text"),
    path("delete_thesis/<int:article_id>", views.delete_article_thesis, name="delete_thesis"),
    path("delete_consent/<int:user_id>", views.delete_consent, name="delete_consent"),
    path("add_thesis/<int:article_id>", views.add_article_thesis, name="add_thesis"),

    path("add_consent/<int:user_id>", views.add_consent, name="add_consent"),
    path("participation", views.confirm_participation, name="confirm_participation"),

    path("add_source/<int:article_id>", views.add_source, name="add_source"),
    path("delete_source/<int:source_id>", views.delete_source, name="delete_source"),
    path("edit_authorship/<int:article_id>", views.edit_authorship, name="edit_authorship"),

    # API Routes
    path('find_user', views.find_user, name="find_user"),
    path('get_text/<int:article_id>', views.get_text, name="get_text"),
    path("edit_general_info", views.edit_general_info, name="edit_general_info"),
    path("edit_secondary_info", views.edit_secondary_info, name="edit_secondary_info"),
    path("edit_section_info", views.edit_section_info, name="edit_section_info"),
    path("edit_article_info", views.edit_article_info, name="edit_article_info"),

    path('check_article_exists', views.check_article_exists, name="check_article_exists"),
    path("register_article", views.register_article, name="register_article"),
    path('join_article', views.join_article, name="join_article"),
    path("approve/<int:article_id>", views.approve_article, name="approve_article"),
    path("reject/<int:article_id>", views.reject_or_restore_article, name="reject_article"),

    path("degree", views.degree, name="degree"),
    path("sections", views.sections, name="sections"),
    path("section/<int:section_id>", views.section, name="section"),
    path("user_articles", views.user_articles, name="user_articles"),
    path("check_technical_work", views.check_technical_work, name="check_technical_work"),
    path("search_articles", views.search_articles, name="search_articles"),

    # Autocomplete API Routes
    path("search_title", views.search_title, name="search_title"),
    path("search_title_translation", views.search_title_translation, name="search_title_translation"),

    # Email Routes
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='conference/password_reset/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='conference/password_reset/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='conference/password_reset/password_reset_complete.html'),name='password_reset_complete'),
    path('password-reset/', PasswordResetView.as_view(template_name='conference/password_reset/password_reset.html',
                                                      html_email_template_name='conference/password_reset/password_reset_email.html',
                                                      subject_template_name='conference/password_reset/password_reset_sebject.txt'), name='password_reset'),
    path("resend_email", views.resend_email, name="resend_email"),
    path("email_change", views.email_change, name="email_change"),

    path("accept_join/<int:user_id>/<int:article_id>/<token>", views.accept_join, name="accept_join"),
    path("accept_invitation/<int:sender_id>/<int:recipient_id>/<int:article_id>/<token>", views.accept_invitation, name="accept_invitation"),
    path("confirm_staff/<int:user_id>/<token>", views.confirm_staff, name="confirm_staff"),

    # Instructions Routes
    path("how-to-register", views.register_instruction, name="register_instruction"),
    path("thesis-requirements", views.thesis_instruction, name="thesis_instruction"),
    path("article-requirements", views.article_instruction, name="article_instruction"),
    path("staff-instruction", views.staff_instruction, name="staff_instruction"),
    path("upload-instruction-thesis", views.upload_thesis_instruction, name="upload_thesis_instruction"),
]

django/mailings/urls.py
from django.urls import path

from . import views


urlpatterns = [

]

django/publisher/urls.py
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
import os.path

from django_email_verification import urls as email_urls

from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('email/', include(email_urls)),
    path('cloud/', include('filemanager.urls')),
    path('mailing/', include('mailings.urls')),

    # For anything not caught by a more specific rule above
    path('', include('conference.urls')),
    path('', include(wagtail_urls)),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

django/conference/forms.py
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django_select2.forms import Select2MultipleWidget

from .models import CustomUser, Section, ArticleText, AuthorInfo, ArticleInfo, ArticleThesis, Consent, TechnicalWork, CommentAttachment


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class ArticleTextForm(forms.ModelForm):
    class Meta:
        model = ArticleText
        fields = ("article", "file")
        widgets = {
            "file": forms.FileInput(attrs={"accept": ".doc,.docx"})
        }


class ArticleThesisForm(forms.ModelForm):
    class Meta:
        model = ArticleThesis
        fields = ("article", "file")
        widgets = {
            "file": forms.FileInput(attrs={"accept": ".doc,.docx"})
        }


class ConsentForm(forms.ModelForm):
    class Meta:
        model = Consent
        fields = ("user", "file")
        widgets = {
            "file": forms.FileInput(attrs={"accept": ".pdf"})
        }


class TechnicalWorkForm(forms.ModelForm):
    class Meta:
        model = TechnicalWork
        fields = ("start", "end")
        widgets = {
            "start": forms.DateTimeField(input_formats=["%d.%m.%Y %H:%M", "%d-%m-%Y"]),
            "end": forms.DateTimeField(input_formats=["%d.%m.%Y %H:%M", "%d-%m-%Y"])
        }


class AuthorInfoForm(forms.Form):
    """Форма для добавления доп. информации об авторе."""
    class Meta:
        model = AuthorInfo
        fields = ("user", "first_name_translation", "last_name_translation",
                  "country", "city", "institution", "department", "department_group",
                  "major", "level", "course", "education_group"
                  )
        widgets = {
            "first_name_translation": forms.CharField(max_length=64, label="Имя на английском языке", label_suffix=":", required=False),
            "last_name_translation": forms.CharField(max_length=64, label="Фамилия на английском языке", label_suffix=":", required=False),
            "country": forms.CharField(max_length=64, label="Страна проживания", initial="Россия", label_suffix=":", required=False),
            "city": forms.CharField(max_length=64, label="Город", initial="Владивосток", label_suffix=":", required=False),
            "institution": forms.CharField(label="Учебное заведение", initial="ДВФУ", label_suffix=":", required=False),
            "department": forms.CharField(label="Подразделение", initial="ШИГН", label_suffix=":", required=False),
            "department_group": forms.CharField(label="Департамент", label_suffix=":", required=False),
            "major": forms.CharField(label="Направление / факультет", label_suffix=":", required=False),
            "level": forms.CharField(max_length=24, label="Уровень образования", initial="Бакалавр", label_suffix=":", required=False),
            "course": forms.IntegerField(min_value=1, label="Курс", label_suffix=":", required=False),
            "education_group": forms.CharField(label="Учебная группа", label_suffix=":", required=False),
        }


class FilterArticleForm(forms.Form):
    """Форма для страницы продвинутого поиска."""
    title = forms.CharField(
        label="Тема",
        label_suffix=":",
        required=False
    )
    keywords__icontains = forms.CharField(label="Ключевые слова", label_suffix=":", required=False)

    title_translation = forms.CharField(label="Тема на английском языке", label_suffix=":", required=False)
    keywords_translation__icontains = forms.CharField(label="Ключевые слова на английском языке", label_suffix=":", required=False)

    section__in = forms.ModelMultipleChoiceField(
        queryset=Section.objects.all(),
        widget=FilteredSelectMultiple("Секция", is_stacked=False),
        required=False,
        label="Секция"
    )

    is_complete = forms.ChoiceField(choices=((None, "Все"), (True, "Да"), (False, "Нет")),
                                 initial=(None, "Все"), label="Принята к публикации", label_suffix=":", required=False)

    is_participation_confirmed = forms.ChoiceField(choices=((None, "Все"), (True, "Да"), (False, "Нет")),
                                  initial=(None, "Все"), label="Участие подтверждено", label_suffix=":", required=False)
    is_winner = forms.ChoiceField(choices=((None, "Все"), (True, "Да"), (False, "Нет")),
                               initial=(None, "Все"), label="Призёр", label_suffix=":", required=False)

    authors__in = forms.ModelMultipleChoiceField(
        queryset=CustomUser.objects.filter(is_staff=False),
        required=False,
        label="Авторы"
    )

    city__icontains = forms.CharField(label="Город", label_suffix=":", max_length=64, required=False)
    institution__icontains = forms.CharField(label="Учебное заведение", label_suffix=":", required=False)
    department__icontains = forms.CharField(label="Подразделение", label_suffix=":", required=False)

    major__icontains = forms.CharField(label="Направление / факультет", label_suffix=":", required=False)
    level__icontains = forms.CharField(label="Уровень образования", label_suffix=":", max_length=24, required=False)
    course = forms.IntegerField(label="Курс", label_suffix=":", min_value=1, required=False)

    adviser_first_name = forms.CharField(label="Имя научного руководителя", label_suffix=":", max_length=64, required=False)
    adviser_middle_name = forms.CharField(label="Отчество научного руководителя", label_suffix=":", max_length=64, required=False)
    adviser_last_name = forms.CharField(label="Фамилия научного руководителя", label_suffix=":", max_length=64, required=False)
    adviser_first_name_translation = forms.CharField(label="Имя научного руководителя на английском языке", label_suffix=":", max_length=64, required=False)
    adviser_last_name_translation = forms.CharField(label="Фамилия научного руководителя на английском языке", label_suffix=":", max_length=64, required=False)
    adviser_degree__icontains = forms.CharField(label="Учёная степень научного руководителя", label_suffix=":", max_length=64, required=False)


class SectionSelect2Form(forms.ModelForm):
    section = forms.ModelChoiceField(
        queryset=Section.objects.all()
    )

    class Meta:
        model = ArticleInfo
        fields = ("section", "authors")


class EmailChangeForm(forms.Form):
    error_messages = {
        'email_mismatch': "Введённые адреса электронной почты не совпадают.",
        'not_changed': "Указан такой же адрес электронной почты, как у вас сейчас."
    }

    new_email1 = forms.EmailField(
        label="Новый адрес электронной почты",
        widget=forms.EmailInput,
    )

    new_email2 = forms.EmailField(
        label="Подтверждение нового адреса электронной почты",
        widget=forms.EmailInput,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(EmailChangeForm, self).__init__(*args, **kwargs)

    def clean_new_email1(self):
        old_email = self.user.email
        new_email1 = self.cleaned_data.get('new_email1')
        if new_email1 and old_email:
            if new_email1 == old_email:
                raise forms.ValidationError(
                    self.error_messages['not_changed'],
                    code='not_changed',
                )
        return new_email1

    def clean_new_email2(self):
        new_email1 = self.cleaned_data.get('new_email1')
        new_email2 = self.cleaned_data.get('new_email2')
        if new_email1 and new_email2:
            if new_email1 != new_email2:
                raise forms.ValidationError(
                    self.error_messages['email_mismatch'],
                    code='email_mismatch',
                )
        return new_email2

    def save(self, commit=True):
        email = self.cleaned_data["new_email1"]
        self.user.email = email
        if commit:
            self.user.save()
        return self.user


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class LimitedMultipleFileInput(forms.FileField):
    def __init__(self, max_files=5, *args, **kwargs):
        self.max_files = max_files
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            if len(data) > self.max_files:
                raise forms.ValidationError(f"Можно прикрепить до {self.max_files} вложений.")
            result = [single_file_clean(item, initial) for item in data]
        else:
            result = single_file_clean(data, initial)
        return result


# class CommentAttachmentForm(forms.ModelForm):
#     class Meta:
#         model = CommentAttachment
#         fields = ('file', )

class CommentAttachmentForm(forms.Form):
    """Форма для отправки комментария авторам доклада с возможностью прикрепить вложения."""
    text = forms.CharField(
        widget=forms.Textarea(attrs={"rows": "5"}),
        label="Комментарий",
        label_suffix=":",
        required=True
    )

    files = LimitedMultipleFileInput(
        label="При желании вы можете прикрепить к комментарию до 5 файлов",
        label_suffix=":",
        required=False
    )

django/conference/templates/conference/library.html
{% extends "conference/layout.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block links %}
<link rel="stylesheet" href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css"/> <!-- Autocomplete -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" /> <!-- Select2 -->
{% endblock %}

{% block body %}
<div class="container-xxl no_paddings">
    <h2 id="header">Поиск материалов конференции</h2>
    {% if message %}
    <div class="red">{{ message }}</div>
    {% endif %}
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <div id="collapseOne" class="accordion-collapse collapse {% if expand_form %}show{% endif %}" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <form action="{% url 'library' %}" method="post">
                        <div class="error_field red" id="submit_error"></div>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <div id="autocomplete_title" class="autocomplete">
                                        {{ form.title|add_label_class:"input_label" }}
                                        {% render_field form.title class="form-control" %}
                                        <ul class="autocomplete-result-list"></ul>
                                    </div>
                                </div>
                                <div class="form-group">
                                    {{ form.keywords__icontains|add_label_class:"input_label" }}
                                    {% render_field form.keywords__icontains class="form-control" %}
                                </div>
                                <hr>
                                <div class="form-group">
                                    {{ form.authors__in|add_label_class:"input_label" }}
                                    {% render_field form.authors__in class="form-control" %}
                                </div>
                                <hr>
                                <div class="form-group">
                                    {{ form.city__icontains|add_label_class:"input_label" }}
                                    {% render_field form.city__icontains class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.institution__icontains|add_label_class:"input_label" }}
                                    {% render_field form.institution__icontains class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.department__icontains|add_label_class:"input_label" }}
                                    {% render_field form.department__icontains class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.major__icontains|add_label_class:"input_label" }}
                                    {% render_field form.major__icontains class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.level__icontains|add_label_class:"input_label" }}
                                    {% render_field form.level__icontains class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.course|add_label_class:"input_label" }}
                                    {% render_field form.course class="form-control" %}
                                </div>
                                <hr>
                                <div class="form-group">
                                    {{ form.is_winner|add_label_class:"input_label" }}
                                    {% render_field form.is_winner class="form-control" %}
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <div id="autocomplete_title_translation" class="autocomplete">
                                        {{ form.title_translation|add_label_class:"input_label" }}
                                        {% render_field form.title_translation class="form-control" %}
                                        <ul class="autocomplete-result-list"></ul>
                                    </div>
                                </div>
                                <div class="form-group">
                                    {{ form.keywords_translation__icontains|add_label_class:"input_label" }}
                                    {% render_field form.keywords_translation__icontains class="form-control" %}
                                </div>
                                <hr>
                                <div class="form-group">
                                    {{ form.section__in|add_label_class:"input_label" }}
                                    {% render_field form.section__in class="form-control" %}
                                </div>
                                <hr>
                                <div class="form-group">
                                    {{ form.adviser_last_name|add_label_class:"input_label" }}
                                    {% render_field form.adviser_last_name class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.adviser_first_name|add_label_class:"input_label" }}
                                    {% render_field form.adviser_first_name class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.adviser_middle_name|add_label_class:"input_label" }}
                                    {% render_field form.adviser_middle_name class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.adviser_last_name_translation|add_label_class:"input_label" }}
                                    {% render_field form.adviser_last_name_translation class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.adviser_first_name_translation|add_label_class:"input_label" }}
                                    {% render_field form.adviser_first_name_translation class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.adviser_degree__icontains|add_label_class:"input_label" }}
                                    {% render_field form.adviser_degree__icontains class="form-control" %}
                                </div>
                                <hr>
                                <div class="form-group">
                                    {{ form.is_complete|add_label_class:"input_label" }}
                                    {% render_field form.is_complete class="form-control" %}
                                </div>
                                <div class="form-group">
                                    {{ form.is_participation_confirmed|add_label_class:"input_label" }}
                                    {% render_field form.is_participation_confirmed class="form-control" %}
                                </div>
                            </div>
                        </div>
                        <div class="form-buttons margin_top">
                            <input type="submit" value="Поиск" class="btn btn-primary margin_right" id="search_btn">
                            <div class="spinner-border m-3" role="status" id="loading" hidden>
                                <span class="visually-hidden">Loading...</span>
                            </div>
                            <a href="{%url 'library' %}"  class="btn btn-secondary">Очистить</a>
                        </div>
                    </form>
                </div>
            </div>

            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Фильтры
                </button>
            </h2>
        </div>
    </div>

    <hr>


    <div class="row">
        <div class="container" id="articles_container">
            {% if articles %}
            <div class="note_container"><span class="note">*показываются первые {{ MAX_SEARCH_RESULTS }} совпадений.</span></div>
            {% for article in articles %}
            <div class="wrapper article_wrapper">
                <div class="article_title">Тема: <a href="{% url 'article' article_id=article.id %}">{{ article.title }}</a></div>
                <div class="article_section">Секция: {{ article.section }}</div>
                <div class="article_keywords">Ключевые слова: {{ article.keywords }}</div>
<!--                <div class="article_deadline">Изменить данные можно до {{ article.deadline }}</div>-->
            </div>
            {% endfor articles|length > 0 %}
            {% elif not_found %}
            <h3>Ничего не найдено</h3>
            {% endif %}
        </div> <!-- Articles container -->
    </div>
</div>

{% endblock %}

{% block script %}
<!--<script defer src="../../static/conference/jQuery.js"></script>-->
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script defer src="https://unpkg.com/@trevoreyre/autocomplete-js"></script> <!-- autocomplete -->

<script defer src="../../static/conference/js/library.js"></script>
<script defer src="../../static/conference/js/library_autocomplete.js"></script>

<script defer>
    var CSRFTOKEN = '{{ csrf_token }}';
    $('#id_section__in').select2({width: '100%', padding: '.375rem .75rem', border: 'var(--bs-border-width) solid var(--bs-border-color);'});
    $('#id_authors__in').select2({width: '100%'});
</script>

{% endblock %}

django/conference/templates/conference/login.html
{% extends "conference/layout.html" %}

{% block body %}

<div class="container">
    <div class="row justify-content-center">
        <div class="wrapper form_wrapper">
            <h4 class="margin_bottom">Вход в учетную запись</h4>

            {% if message %}
                <div class="red">{{ message }}</div>
            {% endif %}
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <input autofocus class="form-control" type="email" name="email" placeholder="e-mail">
                    </div>
                    <div class="form-group mb-3">
                        <input class="form-control" type="password" name="password" placeholder="Пароль">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Вход">
                </form>

            <p class="margin_top">Нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться.</a></p>
            <p>Забыли пароль? <a href="{% url 'password_reset' %}">Востановить пароль.</a></p>
        </div>
    </div>
</div>
{% endblock %}